### PR TITLE
DNS fixes

### PR DESCRIPTION
**Pull request by ktsakalozos**

### CODE REVIEW

**Comment by ktsakalozos** [comment]
@tvansteenburgh I am going to self merge this and you can review this PR when you get time.

**Comment by kwmonroe** [comment]
I just tested this with:
```
microk8s    v1.10.2              39    edge      kjackal    classic
```
Pods look good and the ambassador webui lists worker/ps pods as Running.

**Comment by ktsakalozos** [comment]
Any hints on why it says "kjackal"? How can I change it to canonical?

**Comment by johnsca** [comment]
Because you published it to the store with your account.  I think we'd have to have a team account or something but I can't find any docs on that process.

**Comment by ktsakalozos** [comment]
Yes, @johnsca  first versions were pushed manually by me. But then I connected the lp builders. The owners of the build process is the microk8s-developers. Do I need do need to donate something somewhere? Change the owner of the lp project? We must have done this for the rest of the snaps right?

**Pull request merged**
